server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          fan:
            provider: demo-server
            client-id: fan-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            scope: openid,profile,fan
        provider:
          demo-server:
            issuer-uri: http://127.0.0.1:7000
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:7000