server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: demo-server
            client-id: messaging-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          demo-server:
            issuer-uri: http://172.16.63.132:7000
#      resourceserver:
#        jwt:
#          issuer-uri: http://172.16.63.132:7000